package com.trovantis.logisticsapplication.util;

public enum OrderStatus {
	NEW, QUOTATION, QUOTATION_SENT, ORDER_ASSIGNED, SUCCESSFULLY_COMPLETED, 
	PRICE_QUOTES, AWAITING_CONFIRMATION,
	ORDER_ACCEPTED, SHIPPING_STARTED, SHIPPING_COMPLETED, 
	QUOTATION_EXPIRED, TRACK_ORDER, ORDER_COMPLETED, QUOTATION_PREPARING
}
