CREATE DATABASE logistics1;
use logistics1;
CREATE TABLE `orders` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(30) DEFAULT NULL,
  `MOBILE` bigint DEFAULT NULL,
  `EMAIL` varchar(30) DEFAULT NULL,
  `REQUIREMENT` varchar(100) DEFAULT NULL,
  `SERVICES` varchar(100) DEFAULT NULL,
  `WEIGHT` float DEFAULT NULL,
  `LENGTH` float DEFAULT NULL,
  `WIDTH` float DEFAULT NULL,
  `HEIGHT` float DEFAULT NULL,
  `DETAILS` varchar(300) DEFAULT NULL,
  `DATE_OF_ORDER` date DEFAULT NULL,
  `TIME_OF_ORDER` time DEFAULT NULL,
  `amount` int DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `PICKUP_STREETADDRESS` varchar(100) DEFAULT NULL,
  `PICKUP_REGION` varchar(100) DEFAULT NULL,
  `PICKUP_LOCALITY` varchar(100) DEFAULT NULL,
  `PICKUP_POSTALCODE` int DEFAULT NULL,
  `DROPOFF_STREETADDRESS` varchar(100) DEFAULT NULL,
  `DROPOFF_REGION` varchar(100) DEFAULT NULL,
  `DROPOFF_LOCALITY` varchar(100) DEFAULT NULL,
  `DROPOFF_POSTALCODE` int DEFAULT NULL,
  `IMAGE_OF_LOAD` blob,
  `CUSTOMER_ID` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `fleet_owner` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(30) DEFAULT NULL,
  `LAST_NAME` varchar(30) DEFAULT NULL,
  `PHONE` int DEFAULT NULL,
  `TRAVEL_AGENCY_NAME` varchar(100) DEFAULT NULL,
  `CITY` varchar(30) DEFAULT NULL,
  `STREET_ADDRESS` varchar(100) DEFAULT NULL,
  `REGION` varchar(100) DEFAULT NULL,
  `LOCALITY` varchar(100) DEFAULT NULL,
  `POSTAL_CODE` varchar(10) DEFAULT NULL,
  `IS_ACTIVE` tinyint DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `quotation` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DELIVERY_COST` double DEFAULT NULL,
  `RETURN_DELIVERY_COST` double DEFAULT NULL,
  `PACKAGING_COST` double DEFAULT NULL,
  `ORDER_ID` int DEFAULT NULL,
  `FLEET_OWNER_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `selected_quotation` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int DEFAULT NULL,
  `QUOTATION_ID` int DEFAULT NULL,
  `FLEET_OWNER_ID` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ORDER_ID_UNIQUE` (`ORDER_ID`),
  KEY `QUOTATION_ID` (`QUOTATION_ID`),
  KEY `FLEET_OWNER_ID` (`FLEET_OWNER_ID`),
  CONSTRAINT `selected_quotation_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ID`),
  CONSTRAINT `selected_quotation_ibfk_2` FOREIGN KEY (`QUOTATION_ID`) REFERENCES `quotation` (`ID`),
  CONSTRAINT `selected_quotation_ibfk_3` FOREIGN KEY (`FLEET_OWNER_ID`) REFERENCES `fleet_owner` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `driver` (
  `DRIVER_ID` int NOT NULL AUTO_INCREMENT,
  `GIVEN_NAME` varchar(45) DEFAULT NULL,
  `FAMILY_NAME` varchar(45) DEFAULT NULL,
  `PHONE_NO` varchar(15) DEFAULT NULL,
  `VEHICLE_NO` varchar(45) DEFAULT NULL,
  `ID_PROOF` varchar(45) DEFAULT NULL,
  `ID_DOCUMENT` blob,
  `ORDER_ID` int DEFAULT NULL,
  PRIMARY KEY (`DRIVER_ID`),
  KEY `ORDER_ID_idx` (`ORDER_ID`),
  CONSTRAINT `driver_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `orders` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `fleet_owner_order` (
  `fleet_owner_id` int DEFAULT NULL,
  `order_id` int DEFAULT NULL,
  `fleet_owner_order_id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`fleet_owner_order_id`),
  KEY `order_id_idx` (`order_id`),
  KEY `fleet_owner_id_idx` (`fleet_owner_id`),
  CONSTRAINT `fleet_owner_id` FOREIGN KEY (`fleet_owner_id`) REFERENCES `fleet_owner` (`ID`),
  CONSTRAINT `order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
